### ISSUE TITLE
Problem deploying on heroku

### ISSUE THREAD

**Issue by eldeveloperjuan** [airbnb/babel-plugin-dynamic-import-node#46] opened 2018-04-02 20:28 UTC
Im deploying an application to heroku that uses your plugin, and im getting the following error on execution after successful build :

ReferenceError: Unknown plugin "dynamic-import-node" specified in "/app/package.json" at 0, attempted to resolve relative to "/app"

Plugins for babel are setup like this:

    "plugins": [
      "loadable-components/babel",
      "dynamic-import-node",
      "lodash"
    ],

In my local machine the build process works flawlessly but in heroku fails.

Thanks for any kind of help you can provide.

**Comment by ljharb** [comment] 2018-04-02 21:19
Can you share your full babel config, as well as the command for your build process?

**Comment by eldeveloperjuan** [comment] 2018-04-02 21:33
Of course : 
package.json : https://gist.github.com/eldeveloperjuan/16ae1e27f4f74c7140ace994a7342756
config.babel.js: https://gist.github.com/eldeveloperjuan/8f8ea064ece3e0c2fcfa7e59a9ab3c37


The server is started with this command : yarn start:prod

**Comment by ljharb** [comment] 2018-04-02 23:22
`config.babel.js` is your webpack config but https://gist.github.com/eldeveloperjuan/16ae1e27f4f74c7140ace994a7342756#file-package-json-L117-L141 is your babel config - altho that doesn't tell me anything. I'm confused what `better-npm-run start:prod` does?

**Comment by eldeveloperjuan** [comment] 2018-04-03 00:00
It runs node ./index.js

**Comment by ljharb** [comment] 2018-06-07 06:32
I'm not sure how to help any further; I'm going to close this, but happy to keep discussing.

**Closed by ljharb** 2018-06-07 06:32 UTC

**Comment by risinglf** [comment] 2019-08-29 07:44
Hi maybe this is caused by Heroku that prunes all the devDependencies after the build process:

[https://devcenter.heroku.com/articles/nodejs-support#skip-pruning](https://devcenter.heroku.com/articles/nodejs-support#skip-pruning)
