### ISSUE TITLE
How to use it?

### ISSUE THREAD

**Issue by nsisodiya** [airbnb/babel-plugin-dynamic-import-node#21] opened 2017-06-08 08:37 UTC
Readme do not hint anything how to use it or may be I am dumb.

**Comment by ljharb** [comment] 2017-06-08 23:05
https://github.com/airbnb/babel-plugin-dynamic-import-node#usage should cover it, in concert with normal babel usage; is there a specific question you have?

**Comment by nsisodiya** [comment] 2017-06-09 05:45
I understand, how to add in config file. But what effect this package will bring in babel transformation process. It will be great if you add few line.. what kind of code is not possible without this package. I understand dynamic import but if will be great if a example is added.

**Comment by ljharb** [comment] 2017-06-09 05:47
The specific code output isn't important; the first line in the readme is "Babel plugin to transpile import() to a deferred require()" - basically, it makes `import()` work in node.

**Comment by kopax** [comment] 2017-06-17 14:18
@ljharb I am testing the plugin and I don't see any transpilation. I have seen it in the react-boilerplate, it is used during in the test environmnet.

In what way is this plugin required for test ? I agree with @nsisodiya a small code demo would be not too much.

**Comment by ljharb** [comment] 2017-06-17 16:59
`import()` in babel has no default transpilation. If you don't use this plugin (or a similar one), babel *will not transpile it*.

I'd love to see an example repo where you don't need a transform plugin for it :-)

**Comment by kopax** [comment] 2017-06-17 17:09
@ljharb what is the result of the transpilation ?

I have tested with the following class : 

```es
export default class DemoClass {

  static testStatic = 'This is a static test';

  testAttribute = 'This is a test attribute';

  state = {
    list: ['a', 'b'],
    isSpreadActive: true,
    isTestLiving: true,
  };

  hasInList(value) {
    return this.state.list.includes(value);
  }

  getReplacedEnv() {
    return process.env.NODE_ENV;
  }

  getIsSpreadActive() {
    const { isSpreadActive, ...rest } = this.state; // eslint-disable-line no-unused-vars
    return isSpreadActive;
  }

  getRest() {
    const { isSpreadActive, ...rest } = this.state;
    return rest;
  }

  getTestStatic() {
    return DemoClass.testStatic;
  }

  getTestAttribute() {
    return this.testAttribute;
  }

  setTestAttribute(testAttribute) {
    this.testAttribute = testAttribute;
  }

}
```

and the following test: 

```es
/**
 * Testing example
 */
import DemoClass from '../index';

describe('DemoClass', () => {
  let demoClass;
  beforeEach(() => {
    demoClass = new DemoClass();
  });
  it('should be the DemoClass', () => {
  	expect(demoClass instanceof DemoClass).toBe(true);
  });
  it('should be the static test', () => {
    expect(demoClass.getTestStatic()).toBe('This is a static test');
  });
  it('should be the test attribute', () => {
    expect(demoClass.getTestAttribute()).toBe('This is a test attribute');
  });
  it('should set the test attribute', () => {
    demoClass.setTestAttribute('test')
    expect(demoClass.getTestAttribute()).toBe('test');
  });
  it('should include a in list', () => {
    expect(demoClass.hasInList('a')).toBe(true);
  });
  it('should get replaced env', () => {
    expect(demoClass.getReplacedEnv()).toBe('test');
  });
  it('should get rest from spread', () => {
    expect(demoClass.getIsSpreadActive()).toEqual(true);
  });
  it('should get rest from spread', () => {
    expect(demoClass.getRest()).toEqual({
      isTestLiving: true,
      list: ['a', 'b']
    });
  });
});
```

I have used this `.babelrc`

```json
{
  "only": [
    "src"
  ],
  "presets": [
    [
      "env", {
        "modules": false
      }
    ],
    "stage-2"
  ],
  "plugins": [
    "array-includes",
    "add-module-exports",
    "transform-class-properties"
  ],
  "env": {
    "test": {
      "plugins": [
        "transform-es2015-modules-commonjs",
        "dynamic-import-node"
      ]
    }
  }
}
```

And I produce the following in **lib/index.js**

```js
var _createClass = function () { function defineProperties(target, props) { for (var i = 0; i < props.length; i++) { var descriptor = props[i]; descriptor.enumerable = descriptor.enumerable || false; descriptor.configurable = true; if ("value" in descriptor) descriptor.writable = true; Object.defineProperty(target, descriptor.key, descriptor); } } return function (Constructor, protoProps, staticProps) { if (protoProps) defineProperties(Constructor.prototype, protoProps); if (staticProps) defineProperties(Constructor, staticProps); return Constructor; }; }();

function _objectWithoutProperties(obj, keys) { var target = {}; for (var i in obj) { if (keys.indexOf(i) >= 0) continue; if (!Object.prototype.hasOwnProperty.call(obj, i)) continue; target[i] = obj[i]; } return target; }

function _classCallCheck(instance, Constructor) { if (!(instance instanceof Constructor)) { throw new TypeError("Cannot call a class as a function"); } }

/**
 * Code your first module here
 */

var DemoClass = function () {
  function DemoClass() {
    _classCallCheck(this, DemoClass);

    this.testAttribute = 'This is a test attribute';
    this.state = {
      list: ['a', 'b'],
      isSpreadActive: true,
      isTestLiving: true
    };
  }

  _createClass(DemoClass, [{
    key: 'hasInList',
    value: function hasInList(value) {
      return this.state.list.indexOf(value) !== -1;
    }
  }, {
    key: 'getReplacedEnv',
    value: function getReplacedEnv() {
      return process.env.NODE_ENV;
    }
  }, {
    key: 'getIsSpreadActive',
    value: function getIsSpreadActive() {
      var _state = this.state,
          isSpreadActive = _state.isSpreadActive,
          rest = _objectWithoutProperties(_state, ['isSpreadActive']); // eslint-disable-line no-unused-vars


      return isSpreadActive;
    }
  }, {
    key: 'getRest',
    value: function getRest() {
      var _state2 = this.state,
          isSpreadActive = _state2.isSpreadActive,
          rest = _objectWithoutProperties(_state2, ['isSpreadActive']);

      return rest;
    }
  }, {
    key: 'getTestStatic',
    value: function getTestStatic() {
      return DemoClass.testStatic;
    }
  }, {
    key: 'getTestAttribute',
    value: function getTestAttribute() {
      return this.testAttribute;
    }
  }, {
    key: 'setTestAttribute',
    value: function setTestAttribute(testAttribute) {
      this.testAttribute = testAttribute;
    }
  }]);

  return DemoClass;
}();

DemoClass.testStatic = 'This is a static test';
export default DemoClass;
module.exports = exports['default'];
```

and the following in **lib/tests/index.test.js**

```js
/**
 * Testing example
 */
import DemoClass from '../index';

describe('DemoClass', function () {
  var demoClass = void 0;
  beforeEach(function () {
    demoClass = new DemoClass();
  });
  it('should be the DemoClass', function () {
    expect(demoClass instanceof DemoClass).toBe(true);
  });
  it('should be the static test', function () {
    expect(demoClass.getTestStatic()).toBe('This is a static test');
  });
  it('should be the test attribute', function () {
    expect(demoClass.getTestAttribute()).toBe('This is a test attribute');
  });
  it('should set the test attribute', function () {
    demoClass.setTestAttribute('test');
    expect(demoClass.getTestAttribute()).toBe('test');
  });
  it('should include a in list', function () {
    expect(demoClass.hasInList('a')).toBe(true);
  });
  it('should get replaced env', function () {
    expect(demoClass.getReplacedEnv()).toBe('test');
  });
  it('should get rest from spread', function () {
    expect(demoClass.getIsSpreadActive()).toEqual(true);
  });
  it('should get rest from spread', function () {
    expect(demoClass.getRest()).toEqual({
      isTestLiving: true,
      list: ['a', 'b']
    });
  });
});
```
I don't see any transpilation of the `import` produced by this plugin.

**Comment by ljharb** [comment] 2017-06-17 17:13
@kopax that's because you're talking about `import` - `import()` (note the parens) is a wildly different, stage 3 feature, that takes a string and returns a promise. That's what this transpiles.

**Comment by mherodev** [comment] 2017-06-27 09:41
I am not seeing transpilation. Here's the relevant section of my `package.json`:

```javascript
"babel": {
    "presets": [
      "es2015",
      "react",
      "stage-0"
    ],
    "plugins": [
      "dynamic-import-node",
      ["import-inspector", {
        "serverSideRequirePath": true,
        "webpackRequireWeakId": true
      }]
    ]
  },
```

Here is the relevant code:

```jsx
const UserInfoAsync = Loadable({
  loader: () => import(/* webpackChunkName: 'UserInfo' */ './containers/UserInfo'),
  LoadingComponent: MyLoadingComponent,
  delay: 200,
});
```

And here is the error, lacking an import() transpile:

```jsx
[nodemon] starting `babel-node ./index.js`
/Users/mherold/git/react-cool-starter/src/routes.js:75
    return (0, _importInspector.report)(import( /* webpackChunkName: 'UserInfo' */'./containers/UserInfo'), {
                                        ^^^^^^

SyntaxError: Unexpected token import
```

Any help is appreciated in diagnosing why no transpile is occurring!

Best
Michael

**Comment by mherodev** [comment] 2017-06-27 09:51
Oh interesting, removing the space after the magic comment fixed the transpilation.

Although now I'm seeing a bug unrelated to this library:

```jsx
[nodemon] starting `babel-node ./index.js`
/Users/mherold/git/react-cool-starter/node_modules/react-loadable/lib/index.js:127
    throw new Error('react-loadable requires a `loading` component');
```

Which, it now occurs to me, is because the library has been updated and `LoadingComponent` deprecated. *smh*

A little more futzing around and I'll have this. Seeing an error in the client now, haha. Just delightful.

**Comment by IzaGz** [comment] 2018-07-18 11:05
> ReferenceError: Unknown plugin "dynamic-import-node" specified in "base" at 1, attempted to resolve relative to
`require('babel-register')({
  plugins: ["transform-decorators-legacy", "dynamic-import-node"],
  presets: ['es2015', 'stage-0', 'react'],
  // ignore: /scss/,
  extensions: [".es6", ".es", ".jsx", ".js"]
});
`
please help

**Comment by ljharb** [comment] 2018-07-18 17:43
@IzaGz that’s not related to this issue; you filed #56 (and it’s likely caused by incorrectly babel-transpiling your node modules)

**Comment by olstenlarck** [comment] 2018-07-30 23:31
@nsisodiya you can see it at the source code.

It transforms

```js
const foo = import('./math')

```

to something like

```js
const foo = Promise.resolve().then(() => require('./math'))
```

**Comment by ljharb** [comment] 2018-07-31 04:03
Closing; this seems answered.

**Closed by ljharb** 2018-07-31 04:03 UTC

**Comment by borracciaBlu** [comment] 2018-09-15 23:16
#Code splitting no transpile '!' case.
The following syntax prevent from transpilation as well:

     // Wrong syntax
     import( /* webpackChunkName: 'UserInfo' */'!./containers/UserInfo')

     // Good syntax
     import( /* webpackChunkName: 'UserInfo' */'./containers/UserInfo')

**Comment by ljharb** [comment] 2018-09-16 02:54
Any nonstandard specifier absolutely may break - which is why it's recommended to configure webpack such that you never have nonstandard specifiers.

**Comment by OZZlE** [comment] 2019-07-08 13:43
Does this even work with Webpack 2.7? I only get this:

    react-frontend.js:104 GET http://example.com/0.react-frontend.js net::ERR_ABORTED 404 (Not Found)
    requireEnsure @ react-frontend.js:104
    Object.fallback @ react-frontend.js:84097
    loadAsync @ react-frontend.js:84388
    componentDidMount @ react-frontend.js:84318
    commitLifeCycles @ react-frontend.js:61294
    commitAllLifeCycles @ react-frontend.js:62696
    callCallback @ react-frontend.js:44109
    invokeGuardedCallbackDev @ react-frontend.js:44159
    invokeGuardedCallback @ react-frontend.js:44216
    commitRoot @ react-frontend.js:62908
    (anonymous) @ react-frontend.js:64378
    unstable_runWithPriority @ react-frontend.js:65514
    completeRoot @ react-frontend.js:64377
    performWorkOnRoot @ react-frontend.js:64306
    performWork @ react-frontend.js:64214
    performSyncWork @ react-frontend.js:64188
    requestWork @ react-frontend.js:64057
    scheduleWork @ react-frontend.js:63871
    scheduleRootUpdate @ react-frontend.js:64532
    updateContainerAtExpirationTime @ react-frontend.js:64560
    updateContainer @ react-frontend.js:64617
    ReactRoot.render @ react-frontend.js:64913
    (anonymous) @ react-frontend.js:65050
    unbatchedUpdates @ react-frontend.js:64419
    legacyRenderSubtreeIntoContainer @ react-frontend.js:65046
    render @ react-frontend.js:65115
    renderCatalogApp @ react-frontend.js:41241
    _callee2$ @ react-frontend.js:41358
    tryCatch @ react-frontend.js:1929
    invoke @ react-frontend.js:2155
    prototype.<computed> @ react-frontend.js:1981
    asyncGeneratorStep @ react-frontend.js:2855
    _next @ react-frontend.js:2877
    Promise.then (async)
    asyncGeneratorStep @ react-frontend.js:2865
    _next @ react-frontend.js:2877
    Promise.then (async)
    asyncGeneratorStep @ react-frontend.js:2865
    _next @ react-frontend.js:2877
    Promise.then (async)
    asyncGeneratorStep @ react-frontend.js:2865
    _next @ react-frontend.js:2877
    (anonymous) @ react-frontend.js:2884
    F @ react-frontend.js:863
    (anonymous) @ react-frontend.js:2873
    initApplication @ react-frontend.js:41385
    (anonymous) @ react-frontend.js:41391
    __webpack_require__ @ react-frontend.js:50
    (anonymous) @ react-frontend.js:36258
    __webpack_require__ @ react-frontend.js:50
    (anonymous) @ react-frontend.js:145
    (anonymous) @ react-frontend.js:148
    Show 3 more frames
    react-frontend.js:99 Uncaught Error: Loading chunk 0 failed.
        at HTMLScriptElement.onScriptComplete (react-frontend.js:99)

**Comment by OZZlE** [comment] 2019-07-08 13:50
I'm trying to use is as described here: https://reacttraining.com/react-router/web/guides/code-splitting

**Comment by OZZlE** [comment] 2019-07-08 14:10
Seems my issue was that you need to add the publicPath as shown here:
https://gist.github.com/gaearon/ca6e803f5c604d37468b0091d9959269

should be the weblocation of the file :)
